version: '3.8'
services:
  postgres:
    image: postgres
    container_name: rcv-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: rcv-api
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - SEED=${SEED:-false}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:/app # Mount the current directory for live updates
      - /app/node_modules # Prevent mounting host's node_modules
    networks:
      - app-network

volumes:
  pgdata:
networks:
  app-network:
